version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gridhub
      POSTGRES_USER: gridhub
      POSTGRES_PASSWORD: gridhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: gridhub
      RABBITMQ_DEFAULT_PASS: gridhub

volumes:
  postgres_data: